#Baseline run configuration
base:
  workers: 4
  train_batch: 128
  test_batch: 100
  epochs: 190
  learning_rate: 0.1
  schedule: '55 130'
  resume: ''
  print_freq: 50
  save_dir: './output/cifar10/resnet32'
  save_every: 20
  ite_enable_mixup: 0
  mixup: False
  alpha: 0.3
  smooth: False
  smooth_eps: 0.1

# PatternTrain configuration
pt: 
  num_patterns: 4
  epoch_choose_p_k: 2
  epoch_hard_prune_p_k: 4
  # epoch_choose_p_k: 61
  # epoch_hard_prune_p_k: 141
  grp_lasso_coeff: 0.00025


# prune_ratios:
# # 13.9x 0.00025 xx s 55 130 p_k 61 141 

#   module.layer1.0.conv1.weight: 65
#   module.layer1.0.conv2.weight: 65
#   module.layer1.1.conv1.weight: 65
#   module.layer1.1.conv2.weight: 65
#   module.layer1.2.conv1.weight: 65
#   module.layer1.2.conv2.weight: 65
#   module.layer2.0.conv1.weight: 75
#   module.layer2.0.conv2.weight: 75
#   module.layer2.1.conv1.weight: 75
#   module.layer2.1.conv2.weight: 75
#   module.layer2.2.conv1.weight: 75
#   module.layer2.2.conv2.weight: 75
#   module.layer2.3.conv1.weight: 75 
#   module.layer2.3.conv2.weight: 75 
#   module.layer3.0.conv1.weight: 75 
#   module.layer3.0.conv2.weight: 75 
#   module.layer3.1.conv1.weight: 85 
#   module.layer3.1.conv2.weight: 85 
#   module.layer3.2.conv1.weight: 85 
#   module.layer3.2.conv2.weight: 85 
#   module.layer3.3.conv1.weight: 85
#   module.layer3.3.conv2.weight: 85
#   module.layer3.4.conv1.weight: 85
#   module.layer3.4.conv2.weight: 85
#   module.layer4.0.conv1.weight: 85
#   module.layer4.0.conv2.weight: 85
#   module.layer4.1.conv1.weight: 85
#   module.layer4.1.conv2.weight: 85
#   module.layer4.2.conv1.weight: 85
#   module.layer4.2.conv2.weight: 85

prune_ratios:
# 8.6x 0.00025 xx s 55 130 p_k 61 141 

  module.layer1.0.conv1.weight: 55
  module.layer1.0.conv2.weight: 55
  module.layer1.1.conv1.weight: 55
  module.layer1.1.conv2.weight: 55
  module.layer1.2.conv1.weight: 55
  module.layer1.2.conv2.weight: 55
  module.layer2.0.conv1.weight: 65
  module.layer2.0.conv2.weight: 65
  module.layer2.1.conv1.weight: 65
  module.layer2.1.conv2.weight: 65
  module.layer2.2.conv1.weight: 65
  module.layer2.2.conv2.weight: 65
  module.layer2.3.conv1.weight: 65 
  module.layer2.3.conv2.weight: 65 
  module.layer3.0.conv1.weight: 65 
  module.layer3.0.conv2.weight: 65 
  module.layer3.1.conv1.weight: 75 
  module.layer3.1.conv2.weight: 75 
  module.layer3.2.conv1.weight: 75 
  module.layer3.2.conv2.weight: 75 
  module.layer3.3.conv1.weight: 75
  module.layer3.3.conv2.weight: 75
  module.layer3.4.conv1.weight: 75
  module.layer3.4.conv2.weight: 75
  module.layer4.0.conv1.weight: 75
  module.layer4.0.conv2.weight: 75
  module.layer4.1.conv1.weight: 75
  module.layer4.1.conv2.weight: 75
  module.layer4.2.conv1.weight: 75
  module.layer4.2.conv2.weight: 75