#Baseline run configuration
base:
  workers: 4
  train_batch: 256
  test_batch: 40
  epochs: 95
  learning_rate: 0.1
  schedule: '31 61 75'
  resume: ''
  print_freq: 50
  save_dir: './output/imagenet/resnet50'
  save_every: 20
  mixup: False
  alpha: 0.3
  smooth: False
  smooth_eps: 0.1


# PatternTrain configuration
pt: 
  num_patterns: 4
  # epoch_choose_p_k: 2
  # epoch_hard_prune_p_k: 4
  epoch_choose_p_k: 35
  epoch_hard_prune_p_k: 78
  grp_lasso_coeff: 0.00025


prune_ratios:
  module.layer1.0.conv1.weight: 25
  module.layer1.0.conv2.weight: 25
  module.layer1.0.conv3.weight: 25
  module.layer1.1.conv1.weight: 25
  module.layer1.1.conv2.weight: 25
  module.layer1.1.conv3.weight: 25
  module.layer1.2.conv1.weight: 25
  module.layer1.2.conv2.weight: 25
  module.layer1.2.conv3.weight: 25
  module.layer2.0.conv1.weight: 25
  module.layer2.0.conv2.weight: 25
  module.layer2.0.conv3.weight: 25
  module.layer2.1.conv1.weight: 25
  module.layer2.1.conv2.weight: 25
  module.layer2.1.conv3.weight: 25
  module.layer2.2.conv1.weight: 25
  module.layer2.2.conv2.weight: 25
  module.layer2.2.conv3.weight: 25
  module.layer2.3.conv1.weight: 35
  module.layer2.3.conv2.weight: 35
  module.layer2.3.conv3.weight: 35
  module.layer3.0.conv1.weight: 35
  module.layer3.0.conv2.weight: 35
  module.layer3.0.conv3.weight: 35
  module.layer3.1.conv1.weight: 35
  module.layer3.1.conv2.weight: 35
  module.layer3.1.conv3.weight: 35
  module.layer3.2.conv1.weight: 45
  module.layer3.2.conv2.weight: 45
  module.layer3.2.conv3.weight: 45
  module.layer3.3.conv1.weight: 45
  module.layer3.3.conv2.weight: 45
  module.layer3.3.conv3.weight: 45
  module.layer3.4.conv1.weight: 45
  module.layer3.4.conv2.weight: 45
  module.layer3.4.conv3.weight: 45
  module.layer3.5.conv1.weight: 45
  module.layer3.5.conv2.weight: 45
  module.layer3.5.conv3.weight: 45
  module.layer4.0.conv1.weight: 55
  module.layer4.0.conv2.weight: 55
  module.layer4.0.conv3.weight: 55
  module.layer4.1.conv1.weight: 55
  module.layer4.1.conv2.weight: 55
  module.layer4.1.conv3.weight: 55
  module.layer4.2.conv1.weight: 55
  module.layer4.2.conv2.weight: 55
  module.layer4.2.conv3.weight: 55